import { useUser } from '@clerk/tanstack-react-start'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useAction, useMutation, useQuery } from 'convex/react'
import { Loader2, Upload } from 'lucide-react'
import { useState } from 'react'
// api is generated by `npx convex dev` — run it once before starting the dev server
import { api } from '../../../convex/_generated/api'

export const Route = createFileRoute('/_authenticated/create-podcast')({ component: CreatePodcastPage })

const AI_VOICES = [
  { id: 'alloy',   name: 'Alloy'   },
  { id: 'echo',    name: 'Echo'    },
  { id: 'fable',   name: 'Fable'   },
  { id: 'onyx',    name: 'Onyx'    },
  { id: 'nova',    name: 'Nova'    },
  { id: 'shimmer', name: 'Shimmer' },
]

const CATEGORIES = [
  'Technology', 'Business', 'Education', 'Entertainment',
  'Health', 'Science', 'Sports', 'True Crime', 'Comedy', 'News',
]

function VoiceSelect({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <div className="flex-1">
      <label className="block text-base font-bold text-[#71788B] mb-2">{label}</label>
      <div className="relative">
        <select
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="w-full appearance-none rounded-md bg-[#15171C] px-4 py-3 pr-10 text-sm border border-[#252525] outline-none focus:border-[#f97535] transition-colors cursor-pointer"
          style={{ color: value ? '#fff' : '#71788B' }}
        >
          <option value="" disabled className="bg-[#15171C] text-[#71788B]">Select a voice</option>
          {AI_VOICES.map((v) => (
            <option key={v.id} value={v.id} className="bg-[#15171C] text-white">{v.name}</option>
          ))}
        </select>
        <svg className="pointer-events-none absolute right-3.5 top-1/2 -translate-y-1/2 text-[#71788B]" width="14" height="14" viewBox="0 0 14 14" fill="none">
          <path d="M3 5l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </div>
    </div>
  )
}

function CreatePodcastPage() {
  const { user } = useUser()
  const navigate = useNavigate()

  const convexUser = useQuery(
    api.users.getByClerkId,
    user ? { clerkId: user.id } : 'skip',
  )
  const createPodcast  = useMutation(api.podcasts.create)
  const generatePodcast = useAction(api.podcasts.generatePodcast)

  const [title, setTitle]                     = useState('')
  const [category, setCategory]               = useState('')
  const [description, setDescription]         = useState('')
  const [speaker1, setSpeaker1]               = useState('')
  const [speaker2, setSpeaker2]               = useState('')
  const [script, setScript]                   = useState('')
  const [thumbnailPrompt, setThumbnailPrompt] = useState('')
  const [thumbnailMethod, setThumbnailMethod] = useState<'ai' | 'upload'>('ai')
  const [submitting, setSubmitting]           = useState(false)

  async function handlePublish() {
    if (!convexUser) return
    setSubmitting(true)
    try {
      const id = await createPodcast({
        title,
        description,
        category,
        topicPrompt: script,
        speaker1Voice: speaker1,
        speaker2Voice: speaker2,
        thumbnailPrompt: thumbnailMethod === 'ai' ? thumbnailPrompt || undefined : undefined,
        authorId: convexUser._id,
      })
      // Fire generation in background — detail page shows live status via Convex reactivity
      generatePodcast({ podcastId: id }).catch(console.error)
      navigate({ to: '/podcast/$id', params: { id } })
    } catch (err) {
      console.error('Failed to create podcast', err)
      setSubmitting(false)
    }
  }

  const canPublish = !submitting && !!convexUser && title.trim() && speaker1 && speaker2 && script.trim() && category

  return (
    <div className="px-8 py-8 max-w-2xl">
      <h1 className="text-xl font-bold text-white mb-8">Create Podcast</h1>

      <div className="flex flex-col gap-8">
        {/* Title */}
        <div>
          <label className="block text-base font-bold text-white mb-2.5">
            Podcast Title <span className="text-[#f97535]">*</span>
          </label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Give your podcast a title"
            className="w-full rounded-md bg-[#15171C] px-4 py-3 text-sm text-white placeholder:text-[#71788B] border border-[#252525] outline-none focus:border-[#f97535] transition-colors"
          />
        </div>

        {/* Category */}
        <div>
          <label className="block text-base font-bold text-white mb-2.5">
            Category <span className="text-[#f97535]">*</span>
          </label>
          <div className="relative">
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full appearance-none rounded-md bg-[#15171C] px-4 py-3 pr-10 text-sm border border-[#252525] outline-none focus:border-[#f97535] transition-colors cursor-pointer"
              style={{ color: category ? '#fff' : '#71788B' }}
            >
              <option value="" disabled className="bg-[#15171C] text-[#71788B]">Select a category</option>
              {CATEGORIES.map((c) => (
                <option key={c} value={c} className="bg-[#15171C] text-white">{c}</option>
              ))}
            </select>
            <svg className="pointer-events-none absolute right-3.5 top-1/2 -translate-y-1/2 text-[#71788B]" width="14" height="14" viewBox="0 0 14 14" fill="none">
              <path d="M3 5l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </div>
        </div>

        {/* Description */}
        <div>
          <label className="block text-base font-bold text-white mb-2.5">Description</label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="What is your podcast about?"
            rows={3}
            className="w-full rounded-md bg-[#15171C] px-4 py-3 text-sm text-white placeholder:text-[#71788B] border border-[#252525] outline-none focus:border-[#f97535] transition-colors resize-none"
          />
        </div>

        {/* Speaker voices */}
        <div>
          <label className="block text-base font-bold text-white mb-3">
            Speaker Voices <span className="text-[#f97535]">*</span>
          </label>
          <div className="flex gap-4">
            <VoiceSelect label="Speaker 1 Voice" value={speaker1} onChange={setSpeaker1} />
            <VoiceSelect label="Speaker 2 Voice" value={speaker2} onChange={setSpeaker2} />
          </div>
        </div>

        {/* AI Topic Prompt */}
        <div>
          <label className="block text-base font-bold text-white mb-1">
            AI Topic Prompt <span className="text-[#f97535]">*</span>
          </label>
          <p className="text-[#71788B] text-sm mb-3">
            Describe the topic you want the AI to discuss — it will write and voice the dialogue.
          </p>
          <textarea
            value={script}
            onChange={(e) => setScript(e.target.value)}
            placeholder="e.g. The future of autonomous vehicles and how they will reshape city infrastructure"
            rows={6}
            className="w-full rounded-md bg-[#15171C] px-4 py-3 text-sm text-white placeholder:text-[#71788B] border border-[#252525] outline-none focus:border-[#f97535] transition-colors resize-none"
          />
        </div>

        {/* Thumbnail */}
        <div>
          <label className="block text-base font-bold text-white mb-3">Podcast Thumbnail</label>

          <div className="flex gap-3 mb-4">
            {(['ai', 'upload'] as const).map((method) => (
              <button
                key={method}
                type="button"
                onClick={() => setThumbnailMethod(method)}
                className={`flex-1 rounded-md py-3 text-base font-bold border transition-colors ${
                  thumbnailMethod === method
                    ? 'border-[#f97535] bg-[#f97535]/10 text-[#f97535]'
                    : 'border-[#252525] bg-[#15171C] text-[#71788B] hover:text-white'
                }`}
              >
                {method === 'ai' ? 'AI Generate' : 'Upload Image'}
              </button>
            ))}
          </div>

          {thumbnailMethod === 'ai' ? (
            <input
              type="text"
              value={thumbnailPrompt}
              onChange={(e) => setThumbnailPrompt(e.target.value)}
              placeholder="Describe your thumbnail (e.g. futuristic microphone with neon lights)"
              className="w-full rounded-md bg-[#15171C] px-4 py-3 text-sm text-white placeholder:text-[#71788B] border border-[#252525] outline-none focus:border-[#f97535] transition-colors"
            />
          ) : (
            <label className="flex flex-col items-center justify-center gap-3 rounded-md border-2 border-dashed border-[#252525] bg-[#15171C] p-10 cursor-pointer hover:border-[#f97535]/40 transition-colors">
              <Upload size={24} className="text-[#71788B]" />
              <div className="text-center">
                <p className="text-white text-base font-bold">Click to upload</p>
                <p className="text-[#71788B] text-sm mt-1">PNG, JPG up to 10 MB</p>
              </div>
              <input type="file" accept="image/*" className="hidden" />
            </label>
          )}
        </div>

        {/* Submit */}
        <button
          type="button"
          disabled={!canPublish}
          onClick={handlePublish}
          className="self-start flex items-center gap-2 rounded-md bg-[#f97535] px-[22px] py-[14px] text-base font-bold text-white transition-opacity hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed"
        >
          {submitting && <Loader2 size={16} className="animate-spin" />}
          {submitting ? 'Creating…' : 'Publish Podcast'}
        </button>
      </div>
    </div>
  )
}
