import { useAuth, useUser } from '@clerk/tanstack-react-start'
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { useAction, useMutation, useQuery } from 'convex/react'
import { Crown, Loader2, Lock, Upload } from 'lucide-react'
import { useRef, useState } from 'react'
import { toast } from 'sonner'
// api is generated by `npx convex dev` — run it once before starting the dev server
import { api } from '../../../convex/_generated/api'

export const Route = createFileRoute('/_authenticated/create-podcast')({
  component: CreatePodcastPage,
})

// Mirrors the server's FREE_GENERATION_LIMIT / PRO_GENERATION_LIMIT (convex/podcasts.ts).
// The backend gate is authoritative; this is for the inline wall + remaining-count copy.
const FREE_GENERATION_LIMIT = 3
const PRO_GENERATION_LIMIT = 7

const AI_VOICES = [
  { id: 'alloy', name: 'Alloy' },
  { id: 'echo', name: 'Echo' },
  { id: 'fable', name: 'Fable' },
  { id: 'onyx', name: 'Onyx' },
  { id: 'nova', name: 'Nova' },
  { id: 'shimmer', name: 'Shimmer' },
]

const CATEGORIES = [
  'Technology',
  'Business',
  'Education',
  'Entertainment',
  'Health',
  'Science',
  'Sports',
  'True Crime',
  'Comedy',
  'News',
]

function VoiceSelect({
  label,
  value,
  onChange,
}: {
  label: string
  value: string
  onChange: (v: string) => void
}) {
  return (
    <div className="flex-1">
      <label className="block text-base font-bold text-[#71788B] mb-2">{label}</label>
      <div className="relative">
        <select
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="w-full appearance-none rounded-md bg-[#15171C] px-4 py-3 pr-10 text-sm border border-[#252525] outline-none focus:border-[#f97535] transition-colors cursor-pointer"
          style={{ color: value ? '#fff' : '#71788B' }}
        >
          <option value="" disabled className="bg-[#15171C] text-[#71788B]">
            Select a voice
          </option>
          {AI_VOICES.map((v) => (
            <option key={v.id} value={v.id} className="bg-[#15171C] text-white">
              {v.name}
            </option>
          ))}
        </select>
        <svg
          className="pointer-events-none absolute right-3.5 top-1/2 -translate-y-1/2 text-[#71788B]"
          width="14"
          height="14"
          viewBox="0 0 14 14"
          fill="none"
        >
          <path
            d="M3 5l4 4 4-4"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
        </svg>
      </div>
    </div>
  )
}

function CreatePodcastPage() {
  const { user } = useUser()
  const { has } = useAuth()
  const navigate = useNavigate()

  const convexUser = useQuery(api.users.getByClerkId, user ? { clerkId: user.id } : 'skip')
  const createPodcast = useMutation(api.podcasts.create)
  const generatePodcast = useAction(api.podcasts.generatePodcast)
  const generateUploadUrl = useMutation(api.podcasts.generateThumbnailUploadUrl)
  const setCustomThumbnail = useMutation(api.podcasts.setCustomThumbnail)

  // Pro/quota state — read reactively from the (webhook-synced) users doc, with
  // a live Clerk fallback so the UI reflects an upgrade before the webhook lands.
  const isPro = convexUser?.plan === 'pro' || has?.({ plan: 'pro' }) === true
  const canUploadThumbnail = isPro || has?.({ feature: 'custom_thumbnail' }) === true
  const generationCount = convexUser?.generationCount ?? 0
  const generationLimit = isPro ? PRO_GENERATION_LIMIT : FREE_GENERATION_LIMIT
  const remainingGenerations = Math.max(0, generationLimit - generationCount)
  const atGenerationLimit = remainingGenerations === 0

  const [title, setTitle] = useState('')
  const [category, setCategory] = useState('')
  const [description, setDescription] = useState('')
  const [speaker1, setSpeaker1] = useState('')
  const [script, setScript] = useState('')
  const [thumbnailPrompt, setThumbnailPrompt] = useState('')
  const [thumbnailMethod, setThumbnailMethod] = useState<'ai' | 'upload'>('ai')
  const [thumbnailFile, setThumbnailFile] = useState<File | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const [quotaHit, setQuotaHit] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  async function handlePublish() {
    if (!convexUser) return
    setSubmitting(true)
    setQuotaHit(false)
    try {
      const id = await createPodcast({
        title,
        description,
        category,
        topicPrompt: script,
        thumbnailPrompt:
          thumbnailMethod === 'ai' ? thumbnailPrompt || undefined : undefined,
        speaker1Voice: speaker1,
        authorId: convexUser._id,
      })

      // Pro-only custom thumbnail upload — the server mutation re-checks the plan.
      if (thumbnailMethod === 'upload' && thumbnailFile && canUploadThumbnail) {
        try {
          const uploadUrl = await generateUploadUrl({})
          const res = await fetch(uploadUrl, {
            method: 'POST',
            headers: { 'Content-Type': thumbnailFile.type },
            body: thumbnailFile,
          })
          const { storageId } = (await res.json()) as { storageId: string }
          await setCustomThumbnail({ podcastId: id, storageId: storageId as any })
        } catch (uploadErr) {
          console.error('Custom thumbnail upload failed', uploadErr)
        }
      }

      // Fire generation in background — detail page shows live status via Convex reactivity
      await generatePodcast({ podcastId: id })
      toast.success('Your podcast is generating — this can take a moment.')
      navigate({ to: '/podcast/$id', params: { id } })
    } catch (err) {
      // Defensive: surface the upgrade wall instead of a raw error on a quota race.
      if ((err as { data?: { code?: string } })?.data?.code === 'QUOTA_EXCEEDED') {
        setQuotaHit(true)
      } else {
        console.error('Failed to create podcast', err)
        toast.error('Failed to create podcast. Please try again.')
      }
      setSubmitting(false)
    }
  }

  const showWall = atGenerationLimit || quotaHit
  const canPublish =
    !submitting && !!convexUser && title.trim() && speaker1 && script.trim() && category

  return (
    <div className="px-4 py-6 sm:px-6 md:px-8 md:py-8 max-w-2xl">
      <h1 className="text-xl font-bold text-white mb-8">Create Podcast</h1>

      <div className="flex flex-col gap-8">
        {/* Title */}
        <div>
          <label className="block text-base font-bold text-white mb-2.5">
            Podcast Title <span className="text-[#f97535]">*</span>
          </label>
          <input
            type="text"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Give your podcast a title"
            className="w-full rounded-md bg-[#15171C] px-4 py-3 text-sm text-white placeholder:text-[#71788B] border border-[#252525] outline-none focus:border-[#f97535] transition-colors"
          />
        </div>

        {/* Category */}
        <div>
          <label className="block text-base font-bold text-white mb-2.5">
            Category <span className="text-[#f97535]">*</span>
          </label>
          <div className="relative">
            <select
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              className="w-full appearance-none rounded-md bg-[#15171C] px-4 py-3 pr-10 text-sm border border-[#252525] outline-none focus:border-[#f97535] transition-colors cursor-pointer"
              style={{ color: category ? '#fff' : '#71788B' }}
            >
              <option value="" disabled className="bg-[#15171C] text-[#71788B]">
                Select a category
              </option>
              {CATEGORIES.map((c) => (
                <option key={c} value={c} className="bg-[#15171C] text-white">
                  {c}
                </option>
              ))}
            </select>
            <svg
              className="pointer-events-none absolute right-3.5 top-1/2 -translate-y-1/2 text-[#71788B]"
              width="14"
              height="14"
              viewBox="0 0 14 14"
              fill="none"
            >
              <path
                d="M3 5l4 4 4-4"
                stroke="currentColor"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
        </div>

        {/* Description */}
        <div>
          <label className="block text-base font-bold text-white mb-2.5">Description</label>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="What is your podcast about?"
            rows={3}
            className="w-full rounded-md bg-[#15171C] px-4 py-3 text-sm text-white placeholder:text-[#71788B] border border-[#252525] outline-none focus:border-[#f97535] transition-colors resize-none"
          />
        </div>

        {/* Speaker voice */}
        <div>
          <label className="block text-base font-bold text-white mb-3">
            Voice <span className="text-[#f97535]">*</span>
          </label>
          <VoiceSelect label="Speaker Voice" value={speaker1} onChange={setSpeaker1} />
        </div>

        {/* AI Topic Prompt */}
        <div>
          <label className="block text-base font-bold text-white mb-1">
            AI Topic Prompt <span className="text-[#f97535]">*</span>
          </label>
          <p className="text-[#71788B] text-sm mb-3">
            Describe the topic you want the AI to discuss — it will write and voice the dialogue.
          </p>
          <textarea
            value={script}
            onChange={(e) => setScript(e.target.value)}
            placeholder="e.g. The future of autonomous vehicles and how they will reshape city infrastructure"
            rows={6}
            className="w-full rounded-md bg-[#15171C] px-4 py-3 text-sm text-white placeholder:text-[#71788B] border border-[#252525] outline-none focus:border-[#f97535] transition-colors resize-none"
          />
        </div>

        {/* Thumbnail */}
        <div>
          <label className="block text-base font-bold text-white mb-3">Podcast Thumbnail</label>

          <div className="flex gap-3 mb-4">
            {(['ai', 'upload'] as const).map((method) => {
              const locked = method === 'upload' && !canUploadThumbnail
              return (
                <button
                  key={method}
                  type="button"
                  onClick={() => {
                    if (locked) {
                      navigate({ to: '/billing' })
                      return
                    }
                    setThumbnailMethod(method)
                  }}
                  className={`flex-1 flex items-center justify-center gap-2 rounded-md py-3 text-base font-bold border transition-colors ${
                    thumbnailMethod === method
                      ? 'border-[#f97535] bg-[#f97535]/10 text-[#f97535]'
                      : 'border-[#252525] bg-[#15171C] text-[#71788B] hover:text-white'
                  }`}
                >
                  {locked && <Lock size={13} />}
                  {method === 'ai' ? 'AI Generate' : 'Upload Image'}
                </button>
              )
            })}
          </div>

          {thumbnailMethod === 'ai' || !canUploadThumbnail ? (
            <input
              type="text"
              value={thumbnailPrompt}
              onChange={(e) => setThumbnailPrompt(e.target.value)}
              placeholder="Describe your thumbnail (e.g. futuristic microphone with neon lights)"
              className="w-full rounded-md bg-[#15171C] px-4 py-3 text-sm text-white placeholder:text-[#71788B] border border-[#252525] outline-none focus:border-[#f97535] transition-colors"
            />
          ) : (
            <label className="flex flex-col items-center justify-center gap-3 rounded-md border-2 border-dashed border-[#252525] bg-[#15171C] p-10 cursor-pointer hover:border-[#f97535]/40 transition-colors">
              <Upload size={24} className="text-[#71788B]" />
              <div className="text-center">
                <p className="text-white text-base font-bold">
                  {thumbnailFile ? thumbnailFile.name : 'Click to upload'}
                </p>
                <p className="text-[#71788B] text-sm mt-1">PNG, JPG up to 10 MB</p>
              </div>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                className="hidden"
                onChange={(e) => setThumbnailFile(e.target.files?.[0] ?? null)}
              />
            </label>
          )}

          {!canUploadThumbnail && (
            <p className="mt-2 flex items-center gap-1.5 text-xs text-[#71788B]">
              <Lock size={12} />
              Custom thumbnail upload is a{' '}
              <Link to="/billing" className="font-semibold text-[#f97535] hover:underline">
                Pro
              </Link>{' '}
              feature. Free creators get AI-generated cover art.
            </p>
          )}
        </div>

        {/* Quota meter — Free shows a link to upgrade; Pro shows remaining of 7. */}
        {!showWall && convexUser && (
          <p className="text-sm text-[#71788B]">
            <span className="font-bold text-white">{generationCount}</span> of{' '}
            {generationLimit} {isPro ? 'Pro' : 'free'} podcasts used.{' '}
            {!isPro && (
              <>
                <Link to="/billing" className="font-semibold text-[#f97535] hover:underline">
                  Upgrade to Pro
                </Link>{' '}
                for 7 podcast generations.
              </>
            )}
          </p>
        )}

        {/* Submit / upgrade wall */}
        {showWall ? (
          <div className="rounded-xl border border-[#f97535]/30 bg-[#f97535]/8 p-5">
            <div className="flex items-start gap-3">
              <Crown size={20} className="mt-0.5 shrink-0 text-[#f97535]" />
              <div className="flex-1">
                <p className="text-base font-bold text-white mb-1">
                  You've used all {generationLimit} {isPro ? 'Pro' : 'free'} generations.
                </p>
                <p className="text-sm text-[#71788B] mb-4">
                  {isPro
                    ? "You've reached your Pro plan's generation limit for this period."
                    : 'Upgrade to Pro for 7 podcast generations, custom thumbnail uploads, and the Pro creator badge.'}
                </p>
                {!isPro && (
                  <Link
                    to="/billing"
                    className="inline-flex items-center gap-2 rounded-md bg-[#f97535] px-[22px] py-[14px] text-base font-bold text-white transition-opacity hover:opacity-90"
                  >
                    <Crown size={16} />
                    Upgrade to Pro
                  </Link>
                )}
              </div>
            </div>
          </div>
        ) : (
          <button
            type="button"
            disabled={!canPublish}
            onClick={handlePublish}
            className="self-start flex items-center gap-2 rounded-md bg-[#f97535] px-[22px] py-[14px] text-base font-bold text-white transition-opacity hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {submitting && <Loader2 size={16} className="animate-spin" />}
            {submitting ? 'Creating…' : 'Publish Podcast'}
          </button>
        )}
      </div>
    </div>
  )
}
